export const FETCH_USER = 'FETCH_USER';
export const CART_DISPLAY_REDUCER = 'CART_DISPLAY_REDUCER';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
